# Generated by Django 4.2 on 2025-05-18 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('reward', models.IntegerField(verbose_name='Выигрыш')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История прокрутки',
                'verbose_name_plural': 'Истории прокрутки',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
