# Generated by Django 4.2 on 2025-05-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_level_user_beans_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['number'], 'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
    ]
