# Generated by Django 4.2 on 2025-05-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_level_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_spin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
